# scripts/gen_l10n.py
"""Generates lib/l10n/translations.g.dart for each app from l10n/<lang>.json.

Edit the JSON files (one per language), then run from the repo root:
    python scripts/gen_l10n.py
`--check` exits non-zero if a generated file is out of date or a language is
missing keys / has broken {placeholders} (used by CI).
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
APPS = ["desktop", "mobile"]
PLACEHOLDER = re.compile(r"\{(\w+)\}")


def dart_string(s: str) -> str:
    return "'" + (
        s.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$").replace("\n", "\\n")
    ) + "'"


def build(app: str) -> tuple[str, list[str]]:
    src = ROOT / "apps" / app / "l10n"
    files = sorted(src.glob("*.json"))
    tables = {f.stem: json.loads(f.read_text(encoding="utf-8")) for f in files}
    problems: list[str] = []
    en = tables.get("en")
    if en is None:
        return "", [f"{app}: missing en.json"]
    for lang, table in tables.items():
        for key, text in en.items():
            if key not in table:
                problems.append(f"{app}/{lang}: missing key '{key}'")
                continue
            want = set(PLACEHOLDER.findall(text))
            got = set(PLACEHOLDER.findall(table[key]))
            if want != got:
                problems.append(f"{app}/{lang}: '{key}' placeholders {sorted(got)} != {sorted(want)}")
        for key in table:
            if key not in en:
                problems.append(f"{app}/{lang}: unknown key '{key}' (not in en.json)")

    out = [
        f"// apps/{app}/lib/l10n/translations.g.dart",
        "// GENERATED by scripts/gen_l10n.py from apps/" + app + "/l10n/*.json — do not edit.",
        "// ignore_for_file: lines_longer_than_80_chars",
        "",
        "const Map<String, Map<String, String>> translations = {",
    ]
    order = ["en"] + [k for k in tables if k != "en"]
    for lang in order:
        out.append(f"  '{lang}': {{")
        for key in en:
            if key in tables[lang]:
                out.append(f"    '{key}': {dart_string(tables[lang][key])},")
        out.append("  },")
    out.append("};")
    return "\n".join(out) + "\n", problems


def main() -> int:
    check = "--check" in sys.argv
    failed = False
    for app in APPS:
        code, problems = build(app)
        for p in problems:
            print("ERROR", p)
            failed = True
        target = ROOT / "apps" / app / "lib" / "l10n" / "translations.g.dart"
        if check:
            if not target.exists() or target.read_text(encoding="utf-8") != code:
                print(f"ERROR {target.relative_to(ROOT)} is out of date — run python scripts/gen_l10n.py")
                failed = True
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(code, encoding="utf-8")
            print(f"wrote {target.relative_to(ROOT)}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
