# scripts/gen_l10n.py
"""Generates every piece of language content from the JSON data files.

All text lives in data files, one file per language; nothing is typed into
the code:

  packages/core/l10n/languages.json        languages, picker order, native names
  packages/core/l10n/names/<lang>.json     random device-name words (phone + PC)
  apps/desktop/l10n/<lang>.json            PC app text
  apps/mobile/l10n/<lang>.json             phone app text; keys starting with
                                           "ios." are iOS system prompts

Outputs (generated — do not edit by hand):

  packages/core/lib/src/languages.g.dart
  apps/desktop/lib/l10n/translations.g.dart
  apps/mobile/lib/l10n/translations.g.dart
  apps/mobile/ios/Runner/<lproj>/InfoPlist.strings   (iOS permission prompts)

Run from the repo root after editing:   python scripts/gen_l10n.py
`--check` exits non-zero if an output is out of date, a language is missing a
file or a key, or a {placeholder} is broken (used by CI).
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CORE = ROOT / "packages" / "core"
APPS = ["desktop", "mobile"]
PLACEHOLDER = re.compile(r"\{(\w+)\}")

# Phone-app keys that become iOS Info.plist strings instead of Dart text.
IOS_PREFIX = "ios."
IOS_KEYS = {
    "ios.photos": "NSPhotoLibraryUsageDescription",
    "ios.camera": "NSCameraUsageDescription",
    "ios.local_network": "NSLocalNetworkUsageDescription",
}


def load(path: pathlib.Path):
    return json.loads(path.read_text(encoding="utf-8"))


def languages() -> list[dict]:
    return load(CORE / "l10n" / "languages.json")["languages"]


def dart_string(s: str) -> str:
    return "'" + (
        s.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$").replace("\n", "\\n")
    ) + "'"


def strings_value(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


# ---------------------------------------------------------------- apps

def load_app(app: str, codes: list[str]) -> tuple[dict, list[str]]:
    src = ROOT / "apps" / app / "l10n"
    tables = {f.stem: load(f) for f in sorted(src.glob("*.json"))}
    problems: list[str] = []
    for code in codes:
        if code not in tables:
            problems.append(f"{app}: missing l10n/{code}.json")
    for code in tables:
        if code not in codes:
            problems.append(f"{app}: l10n/{code}.json is not listed in packages/core/l10n/languages.json")
    en = tables.get("en", {})
    for lang, table in tables.items():
        for key, text in en.items():
            if key not in table:
                problems.append(f"{app}/{lang}: missing key '{key}'")
                continue
            want = set(PLACEHOLDER.findall(text))
            got = set(PLACEHOLDER.findall(table[key]))
            if want != got:
                problems.append(f"{app}/{lang}: '{key}' placeholders {sorted(got)} != {sorted(want)}")
        for key in table:
            if key not in en:
                problems.append(f"{app}/{lang}: unknown key '{key}' (not in en.json)")
    if app == "mobile":
        for key in IOS_KEYS:
            if key not in en:
                problems.append(f"mobile/en: missing iOS key '{key}'")
    return tables, problems


def app_dart(app: str, tables: dict, codes: list[str]) -> str:
    en = tables.get("en", {})
    keys = [k for k in en if not k.startswith(IOS_PREFIX)]
    out = [
        f"// apps/{app}/lib/l10n/translations.g.dart",
        "// GENERATED by scripts/gen_l10n.py from apps/" + app + "/l10n/*.json — do not edit.",
        "// ignore_for_file: lines_longer_than_80_chars",
        "",
        "const Map<String, Map<String, String>> translations = {",
    ]
    for lang in codes:
        if lang not in tables:
            continue
        out.append(f"  '{lang}': {{")
        for key in keys:
            if key in tables[lang]:
                out.append(f"    '{key}': {dart_string(tables[lang][key])},")
        out.append("  },")
    out.append("};")
    return "\n".join(out) + "\n"


def ios_strings(table: dict, en: dict) -> str:
    lines = ["/* GENERATED by scripts/gen_l10n.py from apps/mobile/l10n/*.json — do not edit. */"]
    for key, plist_key in IOS_KEYS.items():
        text = table.get(key) or en.get(key, "")
        lines.append(f"{strings_value(plist_key)} = {strings_value(text)};")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- core

def core_dart(langs: list[dict]) -> tuple[str, list[str]]:
    problems: list[str] = []
    out = [
        "// packages/core/lib/src/languages.g.dart",
        "// GENERATED by scripts/gen_l10n.py from packages/core/l10n/ — do not edit.",
        "// ignore_for_file: lines_longer_than_80_chars",
        "",
        "import 'device_names.dart';",
        "import 'i18n.dart';",
        "",
        "/// From packages/core/l10n/languages.json.",
        "const List<LrLanguage> generatedLanguages = [",
    ]
    for l in langs:
        rtl = ", rtl: true" if l.get("rtl") else ""
        out.append(f"  LrLanguage({dart_string(l['code'])}, {dart_string(l['name'])}{rtl}),")
    out += ["];", "", "/// From packages/core/l10n/names/<language>.json.",
            "const Map<String, NameWords> deviceNameWords = {"]
    for l in langs:
        code = l["code"]
        path = CORE / "l10n" / "names" / f"{code}.json"
        if not path.exists():
            problems.append(f"core: missing l10n/names/{code}.json")
            continue
        n = load(path)
        for part in ("first", "second"):
            words = n.get(part, [])
            if len(words) < 2:
                problems.append(f"core/names/{code}: '{part}' needs at least 2 words")
            dupes = {w for w in words if words.count(w) > 1}
            if dupes:
                problems.append(f"core/names/{code}: '{part}' has duplicates {sorted(dupes)}")
        for key in ("pattern", "vowel_pattern"):
            if key in n and ("{a}" not in n[key] or "{b}" not in n[key]):
                problems.append(f"core/names/{code}: '{key}' must contain {{a}} and {{b}}")
        if "pattern" not in n:
            problems.append(f"core/names/{code}: missing 'pattern'")
            continue
        out.append(f"  '{code}': NameWords(")
        for part in ("first", "second"):
            out.append(f"    {part}: [")
            words = n.get(part, [])
            for i in range(0, len(words), 8):
                out.append("      " + " ".join(dart_string(w) + "," for w in words[i:i + 8]))
            out.append("    ],")
        out.append(f"    pattern: {dart_string(n['pattern'])},")
        if "vowel_pattern" in n:
            out.append(f"    vowelPattern: {dart_string(n['vowel_pattern'])},")
            out.append(f"    vowels: {dart_string(n.get('vowels', ''))},")
        out.append("  ),")
    out.append("};")
    names_dir = CORE / "l10n" / "names"
    listed = {l["code"] for l in langs}
    for f in names_dir.glob("*.json"):
        if f.stem not in listed:
            problems.append(f"core: names/{f.name} is not listed in languages.json")
    return "\n".join(out) + "\n", problems


# ---------------------------------------------------------------- main

def outputs() -> tuple[dict[pathlib.Path, str], list[str]]:
    langs = languages()
    codes = [l["code"] for l in langs]
    files: dict[pathlib.Path, str] = {}
    problems: list[str] = []
    if "en" not in codes:
        problems.append("languages.json must contain 'en' (the fallback)")

    code, p = core_dart(langs)
    files[CORE / "lib" / "src" / "languages.g.dart"] = code
    problems += p

    for app in APPS:
        tables, p = load_app(app, codes)
        problems += p
        files[ROOT / "apps" / app / "lib" / "l10n" / "translations.g.dart"] = app_dart(app, tables, codes)
        if app == "mobile":
            runner = ROOT / "apps" / "mobile" / "ios" / "Runner"
            en = tables.get("en", {})
            for l in langs:
                if l["code"] in tables:
                    files[runner / f"{l['ios']}.lproj" / "InfoPlist.strings"] = ios_strings(tables[l["code"]], en)
    return files, problems


def main() -> int:
    check = "--check" in sys.argv
    files, problems = outputs()
    failed = False
    for p in problems:
        print("ERROR", p)
        failed = True
    for target, content in files.items():
        rel = target.relative_to(ROOT)
        if check:
            if not target.exists() or target.read_text(encoding="utf-8") != content:
                print(f"ERROR {rel} is out of date — run python scripts/gen_l10n.py")
                failed = True
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            print(f"wrote {rel}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
